const WORK_OFFICIAL_TYPE_QUESTIONS = 'question';
const WORK_OFFICIAL_TYPE_REPORTS = 'report';
const WORK_OFFICIAL_TYPE_PROPOSITIONS = 'law_proposal';
const WORK_OFFICIAL_TYPE_COSIGNED_PROPOSITIONS = 'cosigned_law_proposal';
const WORK_OFFICIAL_TYPE_COMMISSIONS = 'commission';
const WORK_OFFICIAL_TYPE_PUBLIC_SESSIONS = 'public_session';
const WORK_TYPE_VOTE_SOLEMN = 'vote_solemn';
const WORK_TYPE_VOTE_ORDINARY = 'vote_ordinary';
const WORK_TYPE_VOTE_CENSURE = 'vote_motion_of_censure';
const WORK_TYPE_VOTE_OTHER = 'vote_others';
const WORK_TYPE_VOTE_UNDEFINED = 'vote_undefined';

const WORK_OFFICIAL_TYPES = [ WORK_OFFICIAL_TYPE_QUESTIONS, WORK_OFFICIAL_TYPE_REPORTS, WORK_OFFICIAL_TYPE_PROPOSITIONS, WORK_OFFICIAL_TYPE_COSIGNED_PROPOSITIONS, WORK_OFFICIAL_TYPE_COMMISSIONS, WORK_OFFICIAL_TYPE_PUBLIC_SESSIONS, WORK_TYPE_VOTE_SOLEMN, WORK_TYPE_VOTE_ORDINARY, WORK_TYPE_VOTE_CENSURE, WORK_TYPE_VOTE_OTHER ];

module.exports = {
    WORK_OFFICIAL_TYPES: WORK_OFFICIAL_TYPES,
    WORK_OFFICIAL_TYPE_QUESTIONS: WORK_OFFICIAL_TYPE_QUESTIONS,
    WORK_OFFICIAL_TYPE_REPORTS: WORK_OFFICIAL_TYPE_REPORTS,
    WORK_OFFICIAL_TYPE_PROPOSITIONS: WORK_OFFICIAL_TYPE_PROPOSITIONS,
    WORK_OFFICIAL_TYPE_COSIGNED_PROPOSITIONS: WORK_OFFICIAL_TYPE_COSIGNED_PROPOSITIONS,
    WORK_OFFICIAL_TYPE_COMMISSIONS: WORK_OFFICIAL_TYPE_COMMISSIONS,
    WORK_OFFICIAL_TYPE_PUBLIC_SESSIONS: WORK_OFFICIAL_TYPE_PUBLIC_SESSIONS,

    WORK_TYPE_VOTE_SOLEMN: WORK_TYPE_VOTE_SOLEMN,
    WORK_TYPE_VOTE_ORDINARY: WORK_TYPE_VOTE_ORDINARY,
    WORK_TYPE_VOTE_CENSURE: WORK_TYPE_VOTE_CENSURE,
    WORK_TYPE_VOTE_OTHER: WORK_TYPE_VOTE_OTHER,
}
